### ISSUE TITLE
Inconsistent Standard Errors with NA Outcomes

### ISSUE THREAD

**Issue by Kiohe** [bcallaway11/did#202]
Hi,

I have encountered a potential bug in `att_gt()` that the addition of NAs to a dataset led to identical point estimates but differing standard errors. My understanding is that the NA values are to be ignored in the calculation of point estimates. However, unless I am missing something, I believe it should stand to reason that the standard errors would be unaffected by NA values too.

A set of simulation codes that replicate the issue can be found at : [https://github.com/Kiohe/-did-report](https://github.com/Kiohe/-did-report) .

Thank you for your time and attention to this matter. I appreciate your assistance in resolving this issue.

Best regards,
Kyohei

**Comment by pedrohcgs** [comment]
Hi Kyohei,
This is because you are using bootstrap std errors, so we get different std
error estimates at different runs.
If you want to use analytical std errors, just set bstrap = FALSE
and cband = FALSE in the sims.

I hope this helps.


----------------------------------------------------
*Pedro H. C. Sant'Anna*
*https://psantanna.com <https://psantanna.com>*

----------------------------------------------------
Warning: This email may contain confidential or privileged information
intended only for the use of the individual or entity to whom it is
addressed. If you are not the intended recipient, please understand
that any disclosure, copying, distribution, or use of the contents
of this email is strictly prohibited.
----------------------------------------------------

**Comment by Kiohe** [comment]
Hi Professor Sant'Anna,

Thank you very much for your prompt and insightful responses. With your guidance, I was able to resolve the issue, and I also realized that part of the problem stemmed from my own misunderstanding.

I truly appreciate your support and the time you took to assist me. 

Kyohei
