### ISSUE TITLE
number of observations for group - time estimations

### ISSUE THREAD

**Issue by mmbanasaz** [bcallaway11/did#33]
Hi there,

Is there any way that we can have the number of observations for each group - time estimation?

**Comment by bcallaway11** [comment]
Sorry for the delay getting back to you.  I don't think that we are going to output this in our results, but I think that you should be able to figure this out from your data pretty easily.  

We do print a warning for small group sizes and sometimes report NA results for extremely small group sizes.  

If you are using unbalanced panel, we return the data.frame used in result$DIDparams$data where result is what is returned from a call to `att_gt`, so that could be helpful here too.
