### ISSUE TITLE
Rank-deficient matrix issue

### ISSUE THREAD

**Issue by fschoner** [bcallaway11/did#60]
Dear Brantly Callaway and Pedro Sant'Anna,

running the code below throws the following error message. Must be some collinearity issue but I am unable to trace it down. Any ideas what's going on here? I've sent the data via e-mail.

``` r
library(data.table)
library(did)

df <- fread("df_reg_cs_trust_rep.csv")

sg_attgt <- att_gt(
  yname = "trust.h",
  gname = "first_treat",
  idname = "pid",
  tname = "yr_enrol.h",
  control_group = "notyettreated",
  panel = FALSE,
  xformla = ~ migback,
  data = df,
  est_method = "dr"
)

Error in solve.default(crossprod(wols.x.pre.treat, int.cov)/n) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0
```
Things work if a different dummy is used.
``` r
 sg_attgt_2 <- att_gt(
  yname = "trust.h",
  gname = "first_treat",
  idname = "pid",
  tname = "yr_enrol.h",
  control_group = "notyettreated",
  panel = FALSE,
  xformla = ~ female,
  data = df,
  est_method = "dr"
)
```

**Comment by bcallaway11** [comment]
Just had a chance to go through this.

This is definitely related to some (group,year) combinations having very few cases where `migback=1`. (for example, for the group treated in 2001, there are 0 observations in 1991 where `migback=1` (this happens a few other times too).  Here is some code to see it:
```
df$first_treat <- as.factor(df$first_treat)
df$yr_enrol.h <- as.factor(df$yr_enrol.h)
df$migback <- as.factor(df$migback)

library(tidyverse)
df %>%
  group_by(yr_enrol.h, first_treat, migback, .drop=FALSE) %>%
  summarize(num = n()) %>%
  as.data.frame()
```
When `est_method="dr"`, we call a function from the `DRDID` package called `drdid_rc` that runs a regression of the outcome on covariates separately by being in the pre- and post-treatment periods and separately by whether treated or not treated (so four different regressions), but if there are no treated observations (either pre- or post-period) where `migback=1`, the code will crash.

Interestingly, if you switch to `est_method="reg"`, the code will run again because it only regressions using untreated observations (you have plenty of these, I think).  It will also run  when `est_method="ipw"`.

I'm going to tag @pedrohcgs to see if he has any comments or suggestions here for you here (he is the author of the `DRDID` package, so he may have some thoughts here).

Brant

**Comment by pedrohcgs** [comment]
This is definitely an overlap problem. If `DRDID` was very strict, technically speaking you should get an error in all of these "estimation methods", bc `est_method = "reg"` is extrapolating, and so is `est_method = "ipw"`. Reason that these two kind of work is that we use a law of iterated expectations behind the scenes, but that is only justified if you have overlap (in the population). 

The `drdid_rc` function runs the efficient doubly-robust DiD estimator for repeated cross-sections, which *requires* outcome models for all group-time pairs. Here, we cant apply the LIE trick, and that is why you are getting an error.

I would suggest to avoid the `migback ` covariate.

**Comment by fschoner** [comment]
Thanks to both of you for the fast and helpful responses! 
Maybe you can issue a warning with the error pointing users to potential overlap issues.
