### ISSUE TITLE
Control group other than "notyettreated" and "nevertreated

### ISSUE THREAD

**Issue by HJeongMN** [bcallaway11/did#63]
Hi,

First, thank you so much for the great package! I am super new to R. I only started to use R to use the method from Callaway & Sant'Anna(2020). So please be patient with me if I am asking about something very obvious.

![Screen Shot 2021-05-19 at 1 28 06 AM](https://user-images.githubusercontent.com/84259999/118766118-a07f1480-b841-11eb-9174-c39fd4ae6abf.png)

1) My design is a bit unique; both the treatment group and control group got treated, but treated by different organizations. i.e., the treatment group is treated by firm A, while the control group is treated by firm B with multiple time period and I would like to compare the treatment effects by firm A and firm B that happened in the same year. I am not sure If I can use your package for such design. As you can see, I tried with " control_group = "control" ", and compared with the results when I input "control_group=notyettreated". The results were different (i don't have groups that are "nevertreated"). Does that mean the code worked?  If not, what would be the best way for me to approach?

2) As you can see from the picture, my study period is from 2014 to 2018 and there are groups that are treated in 2018. However, the results only show until 2017. I am not sure why.

3) My data is already matched using CEM and using the weights generated from CEM. Is it okay to include "cem_weights" like that in the code?

I apologize for many questions. I sincerely appreciate your advice in advance.

**Comment by bcallaway11** [comment]
Thanks for the message.  Actually, I think these are complicated questions...ones that I'm not sure that I have good answers for.

> 1. My design is a bit unique; both the treatment group and control group got treated, but treated by different organizations. i.e., the treatment group is treated by firm A, while the control group is treated by firm B with multiple time period and I would like to compare the treatment effects by firm A and firm B that happened in the same year. I am not sure If I can use your package for such design. As you can see, I tried with " control_group = "control" ", and compared with the results when I input "control_group=notyettreated". The results were different (i don't have groups that are "nevertreated"). Does that mean the code worked? If not, what would be the best way for me to approach?

This is interesting, and I don't think our code will work here.  You are right that the issue is with getting the right comparison group neither of the ones that we provide seem right for you.  You could use, say, treated by firm B in any time period as the comparison group by setting `strtyear=0` for all of those, but that isn't exactly what you are looking for.  

> 2. As you can see from the picture, my study period is from 2014 to 2018 and there are groups that are treated in 2018. However, the results only show until 2017. I am not sure why.

Do you have any untreated units in 2018?  No untreated units in the last period would be my first guess about why we don't report any results there.

> 3. My data is already matched using CEM and using the weights generated from CEM. Is it okay to include "cem_weights" like that in the code?

The weights in `weightsname` are usually sampling weights which could be different from the weights based on the propensity score that we use to balance the covariates.

@pedrohcgs any additional comments on 1 and 3?
