### ISSUE TITLE
Conditional parallel trends pre-test p-value

### ISSUE THREAD

**Issue by melsayli** [bcallaway11/did#80]
Dear Brantly and Pedro,

Thank you for the great package and the support you provide to its users! 

I understand that `agg_gt`  provides the p-value for the pre-test for parallel trends assumption, which is based on the group-time ATTs. I have many pre-treatment periods, and following Brantly’s reply to issue #58, I can compute the test statistics to pre-test parallel trends for the periods that are closer to treatment timing (and not for all pre-treatment periods).  

I would like to test whether there are potential violations to parallel trends assumption that pre-test may not be picking up after conditioning on covariates. As with the pre-test for parallel trends, would it be possible to limit the time periods for the `conditional_did_pretest`?   
 
Thank you in advance.

**Comment by bcallaway11** [comment]
Thanks for the message.  I just took a look through the code on this, and I don't think there is as easy of a solution here as there was for the issue that you linked --- just basically due to the way that the code for the `conditional_did_pretest` was written.  

My sense is that most researchers regard our conditional parallel trends test as a bit of overkill.  Even if you were able to shorten the number of pre-treatment periods down, this code would probably take you substantially longer to run.  You could certainly have violations of conditional parallel trends in pre-treatment periods that are not detected by the pre-test that we report in `att_gt`, but I think that most researchers regard the test from `att_gt` as being "good enough".

Hope this helps.  I am extremely busy at the moment, but if you really want to get the conditional pre-test going for a subset of periods, keep me posted and perhaps we could make some progress on it.

Brant

**Comment by melsayli** [comment]
Thank you very much, Brant. 
I agree that pre-test from the `att_gt` is good enough, and it is ok for now.
